# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: camera_stream.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'camera_stream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63\x61mera_stream.proto\x12\x13\x63onstruction_safety\"q\n\x0c\x46rameRequest\x12\x11\n\tcamera_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x13\n\x0bimage_bytes\x18\x03 \x01(\x0c\x12\x14\n\x0cimage_format\x18\x04 \x01(\t\x12\x10\n\x08\x66rame_id\x18\x05 \x01(\x05\"J\n\x10\x42oundingBoxProto\x12\x0c\n\x04xmin\x18\x01 \x01(\x02\x12\x0c\n\x04ymin\x18\x02 \x01(\x02\x12\x0c\n\x04xmax\x18\x03 \x01(\x02\x12\x0c\n\x04ymax\x18\x04 \x01(\x02\"\x83\x01\n\x13\x44\x65tectedObjectProto\x12\r\n\x05label\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x33\n\x04\x62\x62ox\x18\x03 \x01(\x0b\x32%.construction_safety.BoundingBoxProto\x12\x14\n\x0cis_violation\x18\x04 \x01(\x08\"\xe5\x01\n\x13StreamFrameResponse\x12\x11\n\tcamera_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x10\n\x08\x66rame_id\x18\x03 \x01(\x05\x12\x42\n\x10\x64\x65tected_objects\x18\x04 \x03(\x0b\x32(.construction_safety.DetectedObjectProto\x12\x18\n\x10total_violations\x18\x05 \x01(\x05\x12\x19\n\x11inference_time_ms\x18\x06 \x01(\x02\x12\x1d\n\x15\x61nnotated_image_bytes\x18\x07 \x01(\x0c\x32\xc4\x02\n\x13\x43\x61meraStreamService\x12\x63\n\x12UploadCameraStream\x12!.construction_safety.FrameRequest\x1a(.construction_safety.StreamFrameResponse(\x01\x12\x66\n\x13LiveCameraInference\x12!.construction_safety.FrameRequest\x1a(.construction_safety.StreamFrameResponse(\x01\x30\x01\x12`\n\x11\x44\x65tectSingleFrame\x12!.construction_safety.FrameRequest\x1a(.construction_safety.StreamFrameResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'camera_stream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRAMEREQUEST']._serialized_start=44
  _globals['_FRAMEREQUEST']._serialized_end=157
  _globals['_BOUNDINGBOXPROTO']._serialized_start=159
  _globals['_BOUNDINGBOXPROTO']._serialized_end=233
  _globals['_DETECTEDOBJECTPROTO']._serialized_start=236
  _globals['_DETECTEDOBJECTPROTO']._serialized_end=367
  _globals['_STREAMFRAMERESPONSE']._serialized_start=370
  _globals['_STREAMFRAMERESPONSE']._serialized_end=599
  _globals['_CAMERASTREAMSERVICE']._serialized_start=602
  _globals['_CAMERASTREAMSERVICE']._serialized_end=926
# @@protoc_insertion_point(module_scope)
